
package com.convertidor;

import com.vistas.ConvertidorMonedas;
import com.vistas.ConvertidorTemp;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class Convertidor extends javax.swing.JFrame {
    int xMouse, yMouse;
   
    public Convertidor() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(fondo, "src/img/mapa.png");
        SetDate();
    }

    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dataTxt.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE  dd 'de' MMMM 'de' YYYY", spanishLocale)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        dataTxt = new javax.swing.JLabel();
        tituloPpal = new javax.swing.JLabel();
        separadorTituloPpal = new javax.swing.JSeparator();
        btnConvMonedas = new javax.swing.JButton();
        btnConvTemp = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setRequestFocusEnabled(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(0, 0, 0));
        nav.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nav.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navMouseDragged(evt);
            }
        });
        nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtExit.setBackground(new java.awt.Color(0, 0, 0));
        txtExit.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        dataTxt.setBackground(new java.awt.Color(255, 255, 255));
        dataTxt.setForeground(new java.awt.Color(255, 255, 255));
        dataTxt.setText("Hoy es {dayName} {day} de {month} de {year}.");

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dataTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 40));

        tituloPpal.setBackground(new java.awt.Color(255, 255, 255));
        tituloPpal.setFont(new java.awt.Font("Roboto Black", 3, 36)); // NOI18N
        tituloPpal.setForeground(new java.awt.Color(255, 102, 0));
        tituloPpal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPpal.setText("CONVERTIDOR");
        tituloPpal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tituloPpal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(tituloPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 430, 60));

        separadorTituloPpal.setBackground(new java.awt.Color(255, 102, 0));
        separadorTituloPpal.setForeground(new java.awt.Color(255, 102, 0));
        bg.add(separadorTituloPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 400, 30));

        btnConvMonedas.setBackground(new java.awt.Color(0, 0, 153));
        btnConvMonedas.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        btnConvMonedas.setForeground(new java.awt.Color(255, 153, 0));
        btnConvMonedas.setText("CONVERTIDOR DE MONEDAS");
        btnConvMonedas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConvMonedas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvMonedasActionPerformed(evt);
            }
        });
        bg.add(btnConvMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 290, 40));

        btnConvTemp.setBackground(new java.awt.Color(0, 0, 153));
        btnConvTemp.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        btnConvTemp.setForeground(new java.awt.Color(255, 153, 0));
        btnConvTemp.setText("CONVERTIDOR DE TEMPERATURA");
        btnConvTemp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConvTemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvTempActionPerformed(evt);
            }
        });
        bg.add(btnConvTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 290, 40));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapa.png"))); // NOI18N
        bg.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvTempActionPerformed
        ConvertidorTemp ventana3 = new ConvertidorTemp();
        ventana3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConvTempActionPerformed

    private void navMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_navMousePressed

    private void navMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_navMouseDragged

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(Color.red);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void btnConvMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvMonedasActionPerformed
        ConvertidorMonedas ventana2 = new ConvertidorMonedas();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConvMonedasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnConvMonedas;
    private javax.swing.JButton btnConvTemp;
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel nav;
    private javax.swing.JSeparator separadorTituloPpal;
    private javax.swing.JLabel tituloPpal;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables
}
