
package com.vistas;

import com.convertidor.Convertidor;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;


public class ConvertidorTemp extends javax.swing.JFrame {

    int xMouse, yMouse;
            
    public ConvertidorTemp() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetDate();
    }

    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dataTxt.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE  dd 'de' MMMM 'de' YYYY", spanishLocale)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        tituloConvTemp = new javax.swing.JLabel();
        nav = new javax.swing.JPanel();
        dataTxt = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        separadorTitulo = new javax.swing.JSeparator();
        panelConv = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        temperatura = new javax.swing.JTextField();
        listaGrIn = new javax.swing.JComboBox<>();
        listaGrFn = new javax.swing.JComboBox<>();
        btnCambio = new javax.swing.JButton();
        valorTemp = new java.awt.Label();
        unidadResultado = new java.awt.Label();
        volverMenu = new javax.swing.JLabel();
        fondoConvMon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setForeground(new java.awt.Color(0, 0, 0));
        fondo.setName(""); // NOI18N
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloConvTemp.setBackground(new java.awt.Color(255, 255, 255));
        tituloConvTemp.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        tituloConvTemp.setForeground(new java.awt.Color(255, 102, 0));
        tituloConvTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloConvTemp.setText("CONVERTIDOR DE TEMPERATURA");
        tituloConvTemp.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tituloConvTemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fondo.add(tituloConvTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 430, 60));

        nav.setBackground(new java.awt.Color(0, 0, 0));
        nav.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nav.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navMouseDragged(evt);
            }
        });
        nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navMousePressed(evt);
            }
        });

        dataTxt.setBackground(new java.awt.Color(255, 255, 255));
        dataTxt.setForeground(new java.awt.Color(255, 255, 255));
        dataTxt.setText("Hoy es {dayName} {day} de {month} de {year}.");

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtExit.setBackground(new java.awt.Color(0, 0, 0));
        txtExit.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dataTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 40));

        separadorTitulo.setBackground(new java.awt.Color(255, 102, 0));
        separadorTitulo.setForeground(new java.awt.Color(255, 102, 0));
        fondo.add(separadorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 400, 30));

        panelConv.setBackground(new java.awt.Color(0, 0, 0));

        txt1.setBackground(new java.awt.Color(0, 0, 255));
        txt1.setForeground(new java.awt.Color(0, 0, 204));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("Convertir");

        txt.setBackground(new java.awt.Color(0, 0, 255));
        txt.setForeground(new java.awt.Color(0, 0, 204));
        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setText("A");

        temperatura.setBackground(new java.awt.Color(204, 204, 204));
        temperatura.setForeground(new java.awt.Color(0, 0, 0));
        temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturaActionPerformed(evt);
            }
        });

        listaGrIn.setBackground(new java.awt.Color(102, 102, 102));
        listaGrIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ºCelsius", "ºFahrenheit", "Kelvins" }));
        listaGrIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaGrInActionPerformed(evt);
            }
        });

        listaGrFn.setBackground(new java.awt.Color(102, 102, 102));
        listaGrFn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ºCelsius", "ºFahrenheit", "Kelvins" }));
        listaGrFn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaGrFnActionPerformed(evt);
            }
        });

        btnCambio.setBackground(new java.awt.Color(204, 102, 0));
        btnCambio.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        btnCambio.setForeground(new java.awt.Color(0, 0, 0));
        btnCambio.setText("CONVERTIR");
        btnCambio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });

        valorTemp.setAlignment(java.awt.Label.RIGHT);
        valorTemp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        valorTemp.setFont(new java.awt.Font("Roboto Black", 3, 18)); // NOI18N
        valorTemp.setForeground(new java.awt.Color(204, 102, 0));

        unidadResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        unidadResultado.setFont(new java.awt.Font("Roboto Black", 3, 18)); // NOI18N
        unidadResultado.setForeground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout panelConvLayout = new javax.swing.GroupLayout(panelConv);
        panelConv.setLayout(panelConvLayout);
        panelConvLayout.setHorizontalGroup(
            panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConvLayout.createSequentialGroup()
                .addGroup(panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConvLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(unidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConvLayout.createSequentialGroup()
                        .addGroup(panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConvLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaGrFn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConvLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(valorTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConvLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelConvLayout.createSequentialGroup()
                                        .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(listaGrIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConvLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        panelConvLayout.setVerticalGroup(
            panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConvLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaGrIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaGrFn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fondo.add(panelConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 320, 280));

        volverMenu.setForeground(new java.awt.Color(0, 153, 255));
        volverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volverMenu.setText("Volver a Menu");
        volverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverMenu.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        volverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMenuMouseClicked(evt);
            }
        });
        fondo.add(volverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 90, -1));

        fondoConvMon.setBackground(new java.awt.Color(255, 255, 255));
        fondoConvMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapa.png"))); // NOI18N
        fondo.add(fondoConvMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 450, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(Color.red);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void navMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_navMouseDragged

    private void navMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_navMousePressed

    private void listaGrInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaGrInActionPerformed

    }//GEN-LAST:event_listaGrInActionPerformed

    private void temperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperaturaActionPerformed

    private void listaGrFnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaGrFnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaGrFnActionPerformed

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
        
        double valor = Double.parseDouble(temperatura.getText());
        double resultado = 1;
                
        if(listaGrIn.getSelectedItem().toString()== "ºCelsius" && listaGrFn.getSelectedItem().toString() == "ºFahrenheit") {
           resultado = (valor * 1.8) + 32;
        }
        if(listaGrIn.getSelectedItem().toString()== "ºCelsius" && listaGrFn.getSelectedItem().toString() == "Kelvins") {
            resultado = valor + 273.15;
        }
        if(listaGrIn.getSelectedItem().toString()== "ºFahrenheit" && listaGrFn.getSelectedItem().toString() == "ºCelsius") {
            resultado = (valor-32)*5/9;
        }
        if(listaGrIn.getSelectedItem().toString()== "ºFahrenheit" && listaGrFn.getSelectedItem().toString() == "Kelvins") {
            resultado = (valor + 459.67)*5/9;
        }
        if(listaGrIn.getSelectedItem().toString()== "Kelvins" && listaGrFn.getSelectedItem().toString() == "ºCelsius") {
            resultado = valor - 273.15;
        }
        if(listaGrIn.getSelectedItem().toString()== "Kelvins" && listaGrFn.getSelectedItem().toString() == "ºFahrenheit") {
            resultado = 1.8*(valor - 273.15) + 32;
        }
        
        DecimalFormat df = new DecimalFormat("#.00");
        valorTemp.setText(df.format(resultado));
    }//GEN-LAST:event_btnCambioActionPerformed

    private void volverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMenuMouseClicked
        Convertidor ventana1 = new Convertidor();
        ventana1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorTemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambio;
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel fondoConvMon;
    private javax.swing.JComboBox<String> listaGrFn;
    private javax.swing.JComboBox<String> listaGrIn;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel panelConv;
    private javax.swing.JSeparator separadorTitulo;
    private javax.swing.JTextField temperatura;
    private javax.swing.JLabel tituloConvTemp;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txtExit;
    private java.awt.Label unidadResultado;
    private java.awt.Label valorTemp;
    private javax.swing.JLabel volverMenu;
    // End of variables declaration//GEN-END:variables
}
